apiVersion: v1
kind: Pod

metadata:
  name: multicontainer
  namespace: roboshop
  labels:
    purpose: multicontainer
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
