apiVersion: v1
kind: Pod

metadata: 
  name: nginx-annoation
  namespace: roboshop
  lables: 
    jenkinsurl: https://www.jenkins.io/
    info: The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.

spec:
  containers:
    -name: nginx123
    image: nginx
  
