apiVersion: v1
kind: Pod

metadata: 
  name: resource-memory
  namespace: roboshop

spec: 
  containers:
    - name: nginx-memory
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "125Mi"
