apiVersion: v1
kind: Pod

metadata:
  name: pod-config
  namespace: roboshop

spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: configmap-demo 