apiVersion: v1
kind: Pod

metadata:
  name: pod-secret
  namespace: roboshop

spec:
  containers:
    - name: pod-secret
      image: nginx
      envFrom:
        - secretRef:
          name: secret-demo
