apiVersion: v1
kind: Service

metadata:
  name: nginx
  namespace: roboshop

spec:
  selector:
    proj: roboshop
    comp: frontend
    env: dev
  ports:
      - protocol: TCP
        port: 80
        targetPort: 80