apiVersion: v1
kind: Pod

metadata:
  name: pod-service
  namespace: roboshop
  labels: 
        proj: roboshop
        comp: frontend
        env: dev
        
spec:
  containers:
    - name: pod-service
      imge: nginx
      