apiVersion: v1
kind: Pod

metadata:
  name: pod-nodeport
  namespace: roboshop
  labels:
    proj: roboshop
    comp: frontend
    env: dev

spec:
  containers:
    - name: pod-nodeport
      image: nginx
