apiVersion: eksctl.io/vlalpha5
kind: clusterConfig

metadata:
  name: roboshop-dev
  region: us-east-1

managedNodeGroups:
 - name: roboshop-dev
   instanceType: t3.medium
   desiredCapacity: 2
   spot: true
